# Generated by Django 5.2.9 on 2025-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pic',
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(default='no notes...'),
        ),
    ]
