# Generated by Django 5.2.9 on 2025-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, help_text='Upload customer photo', null=True, upload_to='customer_pics/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text="Customer's name", max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(default='no notes...', help_text='Any notes the customer wants to make'),
        ),
    ]
