# Generated by Django 5.2.9 on 2025-12-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of books sold in this transaction')),
                ('price', models.FloatField(help_text='Total sale price (e.g., book price * quantity)')),
                ('date_create', models.DateTimeField(auto_now_add=True, help_text='Date of sale (auto-set)')),
                ('book', models.ForeignKey(help_text='Book being sold', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
