# Generated by Django 5.2.9 on 2025-12-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
